# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-03 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20180831_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=264)),
                ('last', models.CharField(max_length=264)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
